name: Fly Deploy
on:
  push:
    branches:
      - staging
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  FLATPEAK_API_URL: ${{ secrets.FLATPEAK_API_URL }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  PROVIDER_ID: ${{ secrets.PROVIDER_ID }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: echo "NPM_TOKEN $NPM_TOKEN"
        - run: flyctl deploy --remote-only --build-arg NPM_TOKEN
