name: Fly Deploy Staging
on:
  push:
    branches:
      - staging
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only --build-arg NPM_TOKEN=$NPM_TOKEN
